logging:
  file:
    name: mathster-arithmetic-service
    path: ./startup-logs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arithmetic?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true
    url: jdbc:mysql://localhost:3306/arithmetic?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    user: root
    password:

