logging:
  file:
    name: mathster-arithmetic-service
    path: ./startup-logs

spring:
  datasource:
    url: jdbc:mysql://mysqldb/mathster_db?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: T3stM3
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql

  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true
    url: jdbc:mysql://mysqldb/mathster_db?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    user: root
    password: T3stM3

mathster:
  ui:
    url: http://localhost:3000